apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data: 
  # POSTGRESQL Config
  HOST: {{ .Values.postgresql.HOST }}
  PORT: {{ .Values.postgresql.PORT | quote }}
  USER: {{ .Values.postgresql.USER }}
  PASSWORD: {{ .Values.postgresql.PASSWORD }}
