{{ if not .Values.persistence.files.existingClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.files.claimName }}
spec:
  {{- if .Values.persistence.files.storageClass }}
   {{- if (eq "-" .Values.persistence.files.storageClass) }}
  storageClassName: ""
   {{- else }}
  storageClassName: "{{ .Values.persistence.files.storageClass }}"
   {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.files.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.files.size }}
{{ end }}

